### PR TITLE
custom_updates in genn_model.end not defined -> self.custom_updates

### PR DESCRIPTION
**Pull request by FabianSchubert**
### Issue:
`genn_model.end()` throws error because `custom_updates` is not defined.
### Fix:
I assume this should reference the instance variable `self.custom_updates`.

### CODE REVIEW

**Comment by neworderofjamie** [comment]
Good spot - I don't think I've ever actually called that method! I also think this may be the function @tnowotny was looking for..

**Comment by neworderofjamie** [comment]
Once the checks pass, I will merge this **but** it's lifetime may be short as I'm not planning on making any more GeNN 4.X releases and GeNN 5 automatically frees extra-global parameters when the model is destroyed

**Comment by FabianSchubert** [comment]
`egp_dat.needsAllocation` is also not defined - could this be replaced by `not(egp_dat.is_scalar)` because only pointer type EGPs require allocation/freeing of memory?

**Comment by FabianSchubert** [comment]
I did test it on a Genn model that I set up, and it worked, but I missed to actually include some egps to test the other part, because I assumed this was just a small typo - sorry for that, I'll look into it.

**Pull request merged**
