### PR TITLE
Zero copy

### PR DESCRIPTION
**Pull request by neworderofjamie**
Providing your GPU supports the extension, this change allows you to flag state variables to be implemented as a single zero-copy array rather than separate host and device arrays:

```c++
// Store spikes from neuron population 'E' in zero-copied memory
model.setNeuronSpikeZeroCopy("E");

// Store membrane voltage of neurons in population 'E' in zero-copied memory
model.setNeuronVarZeroCopy("E", "V");

// Store synaptic weights for synapse population 'IE' in zero-copied memory
model.setSynapseWeightUpdateVarZeroCopy("IE", "g");
```

Under the hood this changes the way the state variables are allocated and freed and removes the calls to ``cudaMemcpy`` from the ``pullXXXXFromDevice`` and ``pushXXXToDevice`` helpers. Any thoughts on the API/implementation would be much appreciated.

Specifically I am still a little unsure about exactly how the ``__device__`` symbols (the ones with the dd_ prefix) work so I'm a little unsure about how sane the implementation of ``deviceZeroCopy`` here https://github.com/genn-team/genn/blob/zero_copy/lib/src/generateRunner.cc#L450-L461 is.

### CODE REVIEW

**Comment by jamesturner246** [comment]
The `d_` variables are pointers to device memory which are accessible only in host code. The `dd_` variables are also pointers to device memory, but are only accessible in device code. It's a workaround for devices which don't support unified virtual addressing (UVA) - i.e. devices lower than CC 3.0.

About the zero-copy API: I'm wondering what the `"I"` and `"IE"` arguments represent?

**Comment by neworderofjamie** [comment]
Ahh OK - makes sense. They were just the names for my example neuron and
synapse populations.

**Comment by tnowotny** [comment]
Why do the function names contain "initVal"? Isn't it setting a property of the variable rather than its initial value? In other words should they be called
```
model.setNeuronVarZeroCopy("E", "V");
```
etc?

**Comment by neworderofjamie** [comment]
Excellent point - I wasn't really sure what 'official' GeNN terminology was. I'll rename them (and probably also in other places in the new model API)

**Comment by neworderofjamie** [comment]
@tnowotny - renaming is done - what do you think? I'm not 100% sure it's useful in all situations but definitely speeds up recording simulation state on Jetson

**Comment by tnowotny** [comment]
The only slight doubt I had was on ```VarValues```versus ```InitValues``` ... in a sense these are initial values for the variables, so both names make sense.

**Comment by neworderofjamie** [comment]
Yeah - My thinking was:

1. less typing and 
2. the class doesn't, by definition, hold initial values - it just holds a set of model variable values.

**Pull request merged**
