### PR TITLE
Examples manual update

### PR DESCRIPTION
**Pull request by neworderofjamie**
As promised here is the final piece of the GeNN 3.2.0 release

### CODE REVIEW

**Comment by neworderofjamie** [comment]
If you're fiddling....it might be better to just exclude the whole ``tests`` directory from Doxygen..

**Comment by tnowotny** [comment]
I don't know ... I just added some file comments to make clear what's part of the test suite.
Do you think people should look into the test suite?

**Comment by tnowotny** [comment]
I will stop mucking about ... the serious business seems all ok as far as I can tell ...

**Comment by tnowotny** [comment]
Once the tests have passed (indicating I didn't totally break all tests by incorrectly adding doxygen comments through a bash script) it should be fine to merge.

**Comment by neworderofjamie** [comment]
Not particularly and, definitely not, via the doxygen docs! there's just a
lot of classes with the same name which are going to be confusing.

**Pull request merged**
