### PR TITLE
Synapse type simplification

### PR DESCRIPTION
**Pull request by neworderofjamie**
As discussed previously, the previous systems of combining a ``SynapseConnType`` and a``SynapseGType`` was somewhat counter-intuitive, some combinations made no sense and ``INDIVIDUALID`` was, oddly, a ``SynapseGType``.

I believe the following combinations actually make sense (and this PR fixes the code generator so they all work):

- ``SynapseConnType=ALLTOALL/DENSE`` and ``SynapseGType=INDIVIDUALG`` - now called ``DENSE_INDIVIDUALG`` 
- ``SynapseConnType=SPARSE`` and ``SynapseGType=INDIVIDUALG`` - now called ``SPARSE_INDIVIDUALG``
- ``SynapseConnType=SPARSE`` and ``SynapseGType=GLOBALG`` - now called ``SPARSE_GLOBALG``
- ``SynapseGType=INDIVIDUALID`` - now called ``BITMASK_GLOBALG``

The user now just passes ones of these to ``addSynapsePopulation`` (and because they're defined using a scoped C++11 enum, they can't pass anything else).

Internally these enums are defined in terms of a number of flags which the code generator checks. The plan is that by, for example adding a ``FP16`` flag, I'll be able to add special cases for this without having to update all bits of the generator to be aware of it.

Also I've added more feature tests which test the various valid combinations

### CODE REVIEW

**Comment by tnowotny** [comment]
How about ```DENSE/ALLTOALL``` and ```GLOBALG```? Not the most exciting case but could happen?

**Comment by neworderofjamie** [comment]
I wasn't sure if that was a useful case, but if it is, I'm happy to restore it!

By the way, as far as I could tell, the only test the code ever made on ``SynapseConnType`` was whether it was ``SPARSE`` or not so there was no distinction between the behaviour of ``DENSE`` and ``ALLTOALL``.

**Comment by tnowotny** [comment]
Yes, you are right ... ```ALLTOALL``` was never actually necessary. In a sense ```ALLTOALL=DENSE```

**Comment by esinyavuz** [comment]
Also see #92 about different connectivity schemes that used to be there before. It all makes more sense with the latest version of combinations I think.

**Comment by neworderofjamie** [comment]
Thanks for looking at this @esinyavuz - wish I'd seen that earlier - that is exactly the diagram me and Thomas ended up drawing :)

**Comment by neworderofjamie** [comment]
@tnowotny - did you think of a use-case for ``DENSE`` and ``GLOBALG`` or is this ok to merge?

**Comment by tnowotny** [comment]
I think we should not just exclude it even if not that common. I thought it was previously a possibility, or was it not?

**Comment by neworderofjamie** [comment]
Ok - will re-enable that combination - I only left it out because I
couldn't really see a use for it!

**Comment by neworderofjamie** [comment]
Ok it's re-enabled and I have added a test

**Comment by tnowotny** [comment]
ok ... great. I will merge it then.

**Pull request merged**
