### PR TITLE
Avoiding creating unused variables 

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Close https://github.com/genn-team/genn/issues/47.
Ref https://github.com/genn-team/genn/issues/55.

### CODE REVIEW

**Comment by neworderofjamie** [comment]
Hi @tapaswenipathak, thanks for your work on this. It needs a little more thought though - ``shSpk`` is required e.g. [here](https://github.com/genn-team/genn/blob/master/src/genn/backends/cuda/presynapticUpdateStrategy.cc#L219) if any synapse groups have their synapse span type set to postsynaptic and thus the ``PostSpan`` strategy is used.

**Comment by tapaswenipathak** [comment]
@neworderofjamie: Can you tell me the exact point where you see the synapse span is set as postsynaptic present in the `else` condition. Outside or before `else` condition, there are initialisation and use, I agree.

+ How does the PR look now? I will add separate for separate variables.

**Comment by neworderofjamie** [comment]
Well, users are free to set the synapse span from their own models as well as everything else exposed via ``ModelSpec``, ``NeuronGroup``, ``SynapseGroup`` and ``CurrentSource`` (rather than their ``xxxInternal`` counterparts.

**Comment by neworderofjamie** [comment]
I also noticed that our automated testing was not being run on P.R.s created from forks - I have now fixed that and you (should) be able to see a lot of compilation errors caused by the incorrect removal of ``shSpk`` in the warnings e.g. in https://gen-ci.inf.sussex.ac.uk/job/GeNN/job/genn/view/change-requests/job/PR-248/1/artifact/msg_INF900802.txt/*view*/

**Comment by tapaswenipathak** [comment]
@neworderofjamie: review ping.

**Pull request closed without merging**
