### PR TITLE
Fix sparse synapse pre parallelism and shared memory usage

### PR DESCRIPTION
**Pull request by neworderofjamie**
Basically I was adding some tests to test the new ragged matrix connectivity in presynaptic span mode and realised it was broken for small populations (i.e. when it tries to used shared memory to accumulate postsynaptic input).

Many of the isses that caused this are likely to be the fault of past me but:
- If span type was presynaptic, we were toggling the shared memory based on the source population size which is definitely wrong
- We were never initialising the shared memory array if the span type was presynaptic.
- Previously  when postsynaptic parallelism was used, what happens was:
  ```
  linsyn (register) = dd_inSyn (global memory)
  for each spike block {
    shLg (shared mem) = 0
    **accumulate spikes into shLg**
    **synch**
    linsyn += shLg
    **synch**
  }
  dd_inSyn = linsyn
  ```
  Unless I'm missing something, it's unnecessary to synch all the threads and copy back to linsyn after   every block of spikes and, furthermore, it's unnecessary to involve linsyn at all in the sparse case meaning we can just do:
    ```
  shLg (shared mem) = dd_inSyn (global memory)
  for each spike block {
    **accumulate  spikes into shLg**
  }
  dd_inSyn = shLg
  ```

My only remaining concern is that, with presynaptic parallelism, we should perhaps use shared memory atomics to update the shared memory array as it's definitely possible that two threads could try and add input to the same postsynaptic neuron at once.

### CODE REVIEW

**Comment by neworderofjamie** [comment]
@tnowotny - I've merged the other two more trivial PRs to save your time but this one does need your input!

**Comment by tnowotny** [comment]
Jamie, I think you are right on both accounts:
- making the use of shared memory more efficient by cutting out linsyn looks correct.
- I also think atomics will be required in the presynaptic parallelization case. Do you think using shared memory is even worth it on this occasion?

**Comment by neworderofjamie** [comment]
Great! I think, potentially, presynaptic parallelism into shared memory **could** be good for situations with high fan-in i.e. MBONs so I will add the shared memory atomics and benchmark

**Comment by neworderofjamie** [comment]
@tnowotny - I've done some research and, according to https://devblogs.nvidia.com/gpu-pro-tip-fast-histograms-using-shared-atomics-maxwell/, shared memory atomics are slower than global memory atomics on pre-maxwell devices so I've updated the presynaptically parallelised code to use atomics but disabled this unless it's running on Maxwell or newer

**Comment by tnowotny** [comment]
uhm ... on older cards it will do atomics on global memory, correct?

**Comment by neworderofjamie** [comment]
Yes indeed! That's what the ``shouldAccumulateInSharedMemory`` test aims to achieve

**Comment by tnowotny** [comment]
The tests seem to pass and I think the logic seems sound. What did you get on speed benchmarks?

**Comment by neworderofjamie** [comment]
On the Jetson TX1 (Maxwell with poor memory bandwidth so probably the most optimistic choice) - simulating 20000x 100Hz Poisson spike sources, connected to 10 postsynaptic neurons with 10% sparse connectivity - if we use shared memory you get about a 15% speedup.

That's a somewhat contrived example, but this code path was clearly broken before and now can result in **some** speedup.

**Pull request merged**
